services:
  hmi:
    image: ghcr.io/patsec/ot-sim/ot-sim:main
    init: true
    cap_add:
    - NET_ADMIN # for Tailscale
    volumes:
    - /lib/modules:/lib/modules:ro # for Tailscale
    - /dev/net/tun:/dev/net/tun    # for Tailscale
    - ./configs/ot-sim/hmi.xml:/etc/ot-sim/config.xml
    - ./configs/ot-sim/node-red.json:/etc/node-red.json
    ports:
    - 1880:1880
    environment:
    - OTSIM_TAILSCALE_AUTHKEY=${OTSIM_TAILSCALE_AUTHKEY} # for Tailscale
    hostname: ${HOSTNAME} # for Tailscale
